### ISSUE TITLE
Missing filename in error reports from execution. 

### ISSUE THREAD

**Issue by billw2012** [SQFvm/vm#37]
Parsing produces error reports with file name on the next line, but in execution file name is missing. Ideally please have a standardized one line error format so IDEs (and simple regex) can pick it up. 
e.g. https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/

Visual Studio Code can support a number of different formats out of the box as seen here: https://code.visualstudio.com/docs/editor/tasks#_processing-task-output-with-problem-matchers

**Comment by X39** [comment]
this is less of a bug in actual errors but rather one in the actual parser
the line never gets assigned (there are also situations in execution time, where "file" is not known due to used commands, generation etc.)
gonna fix that one

in regards of the "generalized error messages", SQF-VMs goal is to cater towards humans more then it does to automation.
however, after searching in the code, i noticed that there indeed is a problem related to this.
Parsing puts the file AFTER everything else whilst commands put it into the [ERR][L##|C##] part.
Gonna change that probably

**Comment by X39** [comment]
Fixed in 94ca346872920c68b34bf032bb245de8527c3aaa

the second one kinda got addressed in 6976d3cf05f0abe75789c662066b97eeb2bd24c2
