### ISSUE TITLE
Default function parameters not working when accepted type list is provided.

### ISSUE THREAD

**Issue by billw2012** [SQFvm/vm#57]
```sqf
fn = {
    params [["_val", "", [""]]];
    isNil "_val"
};

[] call fn;
```
Should return false, but returns true. _val should take default value of "" and isNil should therefore return false.
This works correctly when the accepted type list is removed (`params [["_val", ""]];`)

**Comment by dedmen** [comment]
If number of elements in _this is smaller than index of value it should fall out here:
https://github.com/SQFvm/vm/blob/9b3c9c3a4ec6c4d04b8cfcd37cb5c134bbbe7909/src/commands/genericcmds.cpp#L1191

Ah! There is the bug
`fels.size() == 2 ? fels.at(1) : std::make_shared<sqf::value>()`
`params [["_val", ""]];` will return default value.
`params [["_val", "", [""]]];` will not because fels.size() will be 3.
